version: 0.2
phases:
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter precache
      - flutter doctor
  build:
    commands:
      - echo Build started on `date`
      - cd guide_infra_web_ui
      - ls
      - echo "SERVER_HOST=https://api.management.guide.inc/api/v1" >> .env
      - flutter build web --release
  post_build:
    commands:
      - echo Build completed on `date`
      - |
        if [ -e "./build/web/index.html" ]; then
          echo Copy ./build/web/ to ${DEPLOY_BUCKET} bucket
          aws s3 cp ./build/web/ s3://${DEPLOY_BUCKET}/ --recursive
        fi
artifacts:
  files:
    - '**/*'
  base-directory: build